### ISSUE TITLE
Crash when pressing meta key (Windows key) under Linux

### ISSUE THREAD

**Issue by NoraCodes** [agmcleod/ld39#1]
When I start the game and then press the meta key (Windows key), the game crashes immediately.

Backtrace:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /checkout/src/libcore/option.rs:335:20
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:610
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:571
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:521
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::panicking::panic
             at /checkout/src/libcore/panicking.rs:51
  10: ld39::main::{{closure}}
  11: winit::platform::platform::EventsLoop::poll_events
  12: ld39::main
  13: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  14: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:458
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  15: __libc_start_main
  16: _start
```

Versions:

```
rustc 1.21.0-nightly (cfe1668ca 2017-07-29)
cargo 0.22.0-nightly (88aa6423a 2017-07-22)
Linux Shadowmere 4.10.0-28-generic #32-Ubuntu SMP Fri Jun 30 05:32:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

If the reason for this isn't immediately obvious to you I'd be happy to work on fixing it :)

**Comment by agmcleod** [comment]
I did push a commit, i think i mentioned it on reddit. To not just blindly unwrap the key. So hopefully this should get ignored. Give it another try whenever you have some time, let me know.

**Comment by NoraCodes** [comment]
It works, thank you!

**Comment by agmcleod** [comment]
:+1: @LeoTindall happy to fix. Thanks for checking it out.
